config/routes.rb
Rails.application.routes.draw do
  resources :fries
  resources :icecreams
  resources :burgers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "burgers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/burger.rb
class Burger < ApplicationRecord
end

app/models/fry.rb
class Fry < ApplicationRecord
end

app/models/icecream.rb
class Icecream < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  before_action :set_burger, only: %i[ show edit update destroy ]

  # GET /burgers or /burgers.json
  def index
    @burgers = Burger.all
  end

  # GET /burgers/1 or /burgers/1.json
  def show
  end

  # GET /burgers/new
  def new
    @burger = Burger.new
  end

  # GET /burgers/1/edit
  def edit
  end

  # POST /burgers or /burgers.json
  def create
    @burger = Burger.new(burger_params)

    respond_to do |format|
      if @burger.save
        format.html { redirect_to burger_url(@burger), notice: "Burger was successfully created." }
        format.json { render :show, status: :created, location: @burger }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /burgers/1 or /burgers/1.json
  def update
    respond_to do |format|
      if @burger.update(burger_params)
        format.html { redirect_to burger_url(@burger), notice: "Burger was successfully updated." }
        format.json { render :show, status: :ok, location: @burger }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /burgers/1 or /burgers/1.json
  def destroy
    @burger.destroy!

    respond_to do |format|
      format.html { redirect_to burgers_url, notice: "Burger was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_burger
      @burger = Burger.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def burger_params
      params.require(:burger).permit(:image, :name, :price, :description, :veggie)
    end
end

app/controllers/fries_controller.rb
class FriesController < ApplicationController
  before_action :set_fry, only: %i[ show edit update destroy ]

  # GET /fries or /fries.json
  def index
    @fries = Fry.all
  end

  # GET /fries/1 or /fries/1.json
  def show
  end

  # GET /fries/new
  def new
    @fry = Fry.new
  end

  # GET /fries/1/edit
  def edit
  end

  # POST /fries or /fries.json
  def create
    @fry = Fry.new(fry_params)

    respond_to do |format|
      if @fry.save
        format.html { redirect_to fry_url(@fry), notice: "Fry was successfully created." }
        format.json { render :show, status: :created, location: @fry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fries/1 or /fries/1.json
  def update
    respond_to do |format|
      if @fry.update(fry_params)
        format.html { redirect_to fry_url(@fry), notice: "Fry was successfully updated." }
        format.json { render :show, status: :ok, location: @fry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fries/1 or /fries/1.json
  def destroy
    @fry.destroy!

    respond_to do |format|
      format.html { redirect_to fries_url, notice: "Fry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fry
      @fry = Fry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fry_params
      params.require(:fry).permit(:image, :name, :price, :description)
    end
end

app/controllers/icecreams_controller.rb
class IcecreamsController < ApplicationController
  before_action :set_icecream, only: %i[ show edit update destroy ]

  # GET /icecreams or /icecreams.json
  def index
    @icecreams = Icecream.all
  end

  # GET /icecreams/1 or /icecreams/1.json
  def show
  end

  # GET /icecreams/new
  def new
    @icecream = Icecream.new
  end

  # GET /icecreams/1/edit
  def edit
  end

  # POST /icecreams or /icecreams.json
  def create
    @icecream = Icecream.new(icecream_params)

    respond_to do |format|
      if @icecream.save
        format.html { redirect_to icecream_url(@icecream), notice: "Icecream was successfully created." }
        format.json { render :show, status: :created, location: @icecream }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @icecream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /icecreams/1 or /icecreams/1.json
  def update
    respond_to do |format|
      if @icecream.update(icecream_params)
        format.html { redirect_to icecream_url(@icecream), notice: "Icecream was successfully updated." }
        format.json { render :show, status: :ok, location: @icecream }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @icecream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icecreams/1 or /icecreams/1.json
  def destroy
    @icecream.destroy!

    respond_to do |format|
      format.html { redirect_to icecreams_url, notice: "Icecream was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_icecream
      @icecream = Icecream.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def icecream_params
      params.require(:icecream).permit(:image, :name, :price, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/helpers/fries_helper.rb
module FriesHelper
end

app/helpers/icecreams_helper.rb
module IcecreamsHelper
end

app/views/burgers/_burger.html.erb
<div class="card mb-4">
  <img class="card-img-top" src="<%= burger.image %>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Nom</h5>
    <p><%= burger.name %></p>
    <p><%= burger.price %> €</p>
    <p><%= burger.description %></p>
    <%= image_tag "veggi.png", alt:"Veggie", class: 'img-fluid veggie' if burger.veggie %>
    <div class="button_montre_moi_ca">
      <p class="montre_moi_ca">
        <%= link_to "Montre moi ça", burger %>
      </p>
    </div>
  </div>
</div>

app/views/burgers/_form.html.erb
<%= stylesheet_link_tag "form", "data-turbo-track": "reload" %>
<%= form_with(model: burger) do |form| %>
  <% if burger.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(burger.errors.count, "error") %> prohibited this burger from being saved:</h2>

      <ul>
        <% burger.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div id="create_burger">
  <div id="form_burger">
    <div>
      <%= form.label :image, style: "display: block"%>
      <%= form.text_area :image, class:"form_zone"%>
    </div>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_area :name, class:"form_zone"%>
    </div>

    <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.text_field :price, class:"form_zone" %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description, class:"form_zone2" %>
    </div>

    <div>
      <%= form.label :veggie, style: "display: block" %>
      <%= form.check_box :veggie %>
    </div>

    <div class="submit-button">
      <%= form.submit class:"submi-button"%>
    </div>
  </div>
</div>
<% end %>

app/views/burgers/edit.html.erb
<h1>Editing burger</h1>

<%= render "form", burger: @burger %>

<br>

<div class="boutons_edit">
  <%= link_to image_tag("montrer_burger.png", class: "montrer_burger"), @burger %>
  <%= link_to image_tag("retour_aux_burger.png", class: "retour_aux_burgers"), burgers_path %>
</div>

app/views/burgers/index.html.erb
<%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>
<p style="color: green"><%= notice %></p>

<div class="burger_moment">
  <div class="burger_moment_card">
    <h1 class="txt_special">Le Roi Du Burger</h1>
    <%= image_tag "Le_special.png", alt:"Le burger spécial" , class: "img_special"%>
    <h2 class="txt_special">Le spécial</h2>
    <p class="card_description txt_special">Hmmmmmmmm il est bon lui.</p>
  </div>
</div>

<h1>Nos Burgers les plus GRRRRR</h1>

<div id="dispo_menu">
  <div class="row">
    <% @burgers.each do |burger| %>
      <div class="col-lg-4">
        <%= render burger %>
      </div>
    <% end %>
  </div>
</div>

<div class="disposition_ajout_burger">
  <%= link_to "Ajouter un Burger +", new_burger_path, class: "bouton_ajout_burger" %>
</div>

  <div id="disposition_map">
    <div id="map">
      <h1 id="on_va_ou">On va où ???</h1>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2827.160605841225!2d-0.567809343563199!3d44.879380445905745!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd5529fd793afcb3%3A0xc85e33c336150653!2sBurger%20King!5e0!3m2!1sfr!2sfr!4v1708594111403!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>

app/views/burgers/new.html.erb
<%= stylesheet_link_tag "form", "data-turbo-track": "reload" %>
<h1>Créer un nouveau burger</h1>

<%= render "form", burger: @burger %>

<br>

<div>
  <%= link_to image_tag("retour_arriere.png", class: "retour"), burgers_path%>
</div>

app/views/burgers/show.html.erb
<%= stylesheet_link_tag "show", "data-turbo-track": "reload" %>
<p style="color: green"><%= notice %></p>

<div class="show_burger">
<%= render @burger %>
</div>

<div class="disposition_edit_sup">

  <%= link_to image_tag("modifier_burger.png", class: "modifier_burger"), edit_burger_path(@burger) %>

  <%= button_to image_tag("supprimer_burger.png", class: "supprimer_burger"), @burger, method: :delete, class:"destroy" %>

</div>

<%= link_to image_tag("retour_aux_burger.png", class: "retour_aux_burgers"), burgers_path %>

app/views/fries/_form.html.erb
<%= stylesheet_link_tag "form", "data-turbo-track": "reload" %>
<%= form_with(model: fry) do |form| %>
  <% if fry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fry.errors.count, "error") %> prohibited this fry from being saved:</h2>

      <ul>
        <% fry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div id="create_burger">
  <div id="form_burger">
    <div>
      <%= form.label :image, style: "display: block"%>
      <%= form.text_area :image, class:"form_zone"%>
    </div>

    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_area :name, class:"form_zone"%>
    </div>

    <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.text_field :price, class:"form_zone" %>
    </div>

    <div>
      <%= form.label :description, style: "display: block" %>
      <%= form.text_area :description, class:"form_zone2" %>
    </div>

    <div class="submit-button">
      <%= form.submit class:"submi-button"%>
    </div>
  </div>
</div>
<% end %>

app/views/fries/_fry.html.erb
<%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>
<div class="card mb-4">
  <img class="card-img-top" src="<%= fry.image %>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Nom</h5>
    <p><%= fry.name %></p>
    <p><%= fry.price %> €</p>
    <p><%= fry.description %></p>
    <div class="button_montre_moi_ca">
      <p class="montre_moi_ca">
        <%= link_to "Montre moi ça", fry %>
      </p>
    </div>
  </div>
</div>

app/views/fries/edit.html.erb
<h1>Editing fry</h1>

<%= render "form", fry: @fry %>

<br>

<div>
  <%= link_to image_tag("montrer_frite.png", class: "montrer_burger"), @fry %> |
  <%= link_to image_tag("retour_aux_frites.png", class: "retour_aux_burgers"), fries_path %>
</div>

app/views/fries/index.html.erb
<%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>
<p style="color: green"><%= notice %></p>

<div class="burger_moment">
  <div class="burger_moment_card">
    <h1 class="txt_special">La princesse des frites</h1>
    <%= image_tag "frite_special.png", alt:"frite spécial" , class: "img_special"%>
    <h2 class="txt_special">La spéciale</h2>
    <p class="card_description txt_special">Elle est bonne elle.</p>
  </div>
</div>

<h1>Nos Encas les plus crounch crounch</h1>

<div id="dispo_menu">
  <div class="row">
    <% @fries.each do |fry| %>
      <div class="col-lg-4">
        <%= render fry %>
      </div>
    <% end %>
  </div>
</div>

<div class="disposition_ajout_burger">
  <%= link_to "Ajouter un encas +", new_fry_path, class: "bouton_ajout_burger" %>
</div>

  <div id="disposition_map">
    <div id="map">
      <h1 id="on_va_ou">On va où ???</h1>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2827.160605841225!2d-0.567809343563199!3d44.879380445905745!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd5529fd793afcb3%3A0xc85e33c336150653!2sBurger%20King!5e0!3m2!1sfr!2sfr!4v1708594111403!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>

app/views/fries/new.html.erb
<%= stylesheet_link_tag "form", "data-turbo-track": "reload" %>
<h1>Créer un nouveau encas</h1>

<%= render "form", fry: @fry %>

<br>

<div>
  <%= link_to image_tag("retour_arriere.png", class: "retour"), fries_path %>
</div>

app/views/fries/show.html.erb
<%= stylesheet_link_tag "show", "data-turbo-track": "reload" %>
<p style="color: green"><%= notice %></p>

<%= render @fry %>

<div class="disposition_edit_sup">
  <%= link_to image_tag("modifier_frite.png", class: "modifier_burger"), edit_fry_path(@fry) %> 
  <%= link_to image_tag("retour_aux_frites.png", class: "retour_aux_burgers"), fries_path %>

  <%= button_to image_tag("supprimer_frite.png", class: "supprimer_burger"), @fry, method: :delete, class:"destroy" %>
</div>

app/views/icecreams/_form.html.erb
<%= stylesheet_link_tag "form", "data-turbo-track": "reload" %>
<%= form_with(model: icecream) do |form| %>
  <% if icecream.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(icecream.errors.count, "error") %> prohibited this icecream from being saved:</h2>

      <ul>
        <% icecream.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div id="create_burger">
  <div id="form_burger">
  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_area :image, class:"form_zone"%>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class:"form_zone"%>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, class:"form_zone" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class:"form_zone" %>
  </div>

  <div class="submit-button">
      <%= form.submit class:"submi-button"%>
    </div>
  </div>
  </div>
<% end %>

app/views/icecreams/_icecream.html.erb
<%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>
<div class="card mb-4">
  <img class="card-img-top" src="<%= icecream.image %>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Nom</h5>
    <p><%= icecream.name %></p>
    <p><%= icecream.price %> €</p>
    <p><%= icecream.description %></p>
    <div class="button_montre_moi_ca">
      <p class="montre_moi_ca">
        <%= link_to "Montre moi ça", icecream %>
      </p>
    </div>
  </div>
</div>

app/views/icecreams/edit.html.erb
<h1>Editing icecream</h1>

<%= render "form", icecream: @icecream %>

<br>

<div class="boutons_edit">
  <%= link_to image_tag("montrer_glace.png", class: "montrer_burger"), @icecream %>
  <%= link_to image_tag("retour_aux_glaces", class: "retour_aux_burgers"), @icecream %>
</div>

app/views/icecreams/index.html.erb
<%= stylesheet_link_tag "indexi", "data-turbo-track": "reload" %>
<p style="color: green"><%= notice %></p>


<div class="burger_moment">
  <div class="burger_moment_card">
    <h1 class="txt_special">La Reine des glaces</h1>
    <%= image_tag "special_icecream.png", alt:"La glace spécial" , class: "img_special" %>
    <h2 class="txt_special">La spéciale</h2>
    <p class="card_description txt_special">Elle est bonne elle.</p>
  </div>
</div>


<h1>Nos Glaces les plus GLAGLAGLA</h1>

<div id="dispo_menu">
  <div class="row">
  <% @icecreams.each do |icecream| %>
      <div class="col-lg-4">
        <%= render icecream %>
      </div>
    <% end %>
  </div>
</div>

<div class="disposition_ajout_icecream">
  <%= link_to "Ajouter une Glace +", new_icecream_path, class: "bouton_ajout_icecream" %>
</div>

  <div id="disposition_map">
    <div id="map">
      <h1 id="on_va_ou">On va où ???</h1>
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2827.160605841225!2d-0.567809343563199!3d44.879380445905745!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd5529fd793afcb3%3A0xc85e33c336150653!2sBurger%20King!5e0!3m2!1sfr!2sfr!4v1708594111403!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
  </div>

app/views/icecreams/new.html.erb
<h1>Créer une nouvelle icecream</h1>

<%= render "form", icecream: @icecream %>

<br>

<div>
  <%= link_to image_tag("retour_arriere.png", class: "retour"), icecreams_path %>
</div>

app/views/icecreams/show.html.erb
<%= stylesheet_link_tag "show", "data-turbo-track": "reload" %>
<p style="color: green"><%= notice %></p>

<%= render @icecream %>

<div class="disposition_edit_sup">

  <%= link_to image_tag("modifier_glace.png", class: "modifier_burger"), edit_icecream_path(@icecream) %>

  <%= button_to image_tag("supprimer_glace.png", class: "supprimer_burger"), @icecream, method: :delete, class:"destroy" %>

</div>

<%= link_to image_tag("retour_aux_glaces.png", class: "retour_aux_burgers"), icecreams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Le Roi Du Burger</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('logo_roi_du_burger.png') %>
  </head>

  <body>
      <header>

          <div class="button_header">

          <%= image_tag "logo_roi_du_burger.png", alt:"Logo du Roi du Burger" %>

          <%= link_to "Voir les Glaces", icecreams_path, class: "creat_burger" %>

          <%= link_to "Voir les Burgers", burgers_path, class: "creat_burger" %>

          <%= link_to "Voir les Frites", fries_path, class: "creat_burger" %>

          </div>
      </header>
      <main class="container">
         <%= yield %>
      </main>
      <footer>
        <p class="txt_footer">&copy; 2024 Le Roi Du Burger. Tout droits réservé.</p>
      </footer>



</html>